from enum import Enum


class TSCVulnTool(Enum):
    """Enumeration of Tenable SC vulnerability tools"""

    CCEIPDETAIL           = "cceipdetail"
    CVEIPDETAIL           = "cveipdetail"
    IAVMIPDETAIL          = "iavmipdetail"
    IPLIST                = "iplist"
    LISTMAILCLIENTS       = "listmailclients"
    LISTSERVICES          = "listservices"
    LISTOS                = "listos"
    LISTSOFTWARE          = "listsoftware"
    LISTSSHSERVERS        = "listsshservers"
    LISTVULN              = "listvuln"
    LISTWEBCLIENTS        = "listwebclients"
    LISTWEBSERVERS        = "listwebservers"
    SUMASSET              = "sumasset"
    SUMCCE                = "sumcce"
    SUMCLASSA             = "sumclassa"
    SUMCLASSB             = "sumclassb"
    SUMCLASSC             = "sumclassc"
    SUMCVE                = "sumcve"
    SUMDNSNAME            = "sumdnsname"
    SUMFAMILY             = "sumfamily"
    SUMIAVM               = "sumiavm"
    SUMID                 = "sumid"
    SUMIP                 = "sumip"
    SUMMSBULLETIN         = "summsbulletin"
    SUMPROTOCOL           = "sumprotocol"
    SUMREMEDIATION        = "sumremediation"
    SUMSEVERITY           = "sumseverity"
    SUMUSERRESPONSIBILITY = "sumuserresponsibility"
    SUMPORT               = "sumport"
    TREND                 = "trend"
    VULNDETAILS           = "vulndetails"
    VULNIPDETAIL          = "vulnipdetail"
    VULNIPSUMMARY         = "vulnipsummary"
    SUMWASURL             = "sumwasurl"
    WASVULNDETAIL         = "wasvulndetail"
    WASLISTVULN           = "waslistvuln"
